### ISSUE TITLE
When reloading a chunk changes made to terrain using left click and right click are overwritten

### ISSUE THREAD

**Issue by JzAli** [Eldemarkki/Marching-Cubes-Terrain#47]
If i make changes to a chunk using the deforming tool you have made , and then i fly away from it. the chunk resets to what it was when it was created instead of saving the changes i made from the tools.

**Comment by Eldemarkki** [comment]
This is, in a way, intended behaviour. You would need to implement a save and load system (#10). I’ve started implementing one a few weeks ago, but I haven’t really had the motivation to code anything since then, so it might be a very long time (I’m talking like months, maybe even next year) before it gets done. Closing this, as it’s a duplicate of #10
